/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddBtn: typeof import('./components/common/button/AddBtn.vue')['default']
    AppFooter: typeof import('./components/main/AppFooter.vue')['default']
    BackBtn: typeof import('./components/common/button/BackBtn.vue')['default']
    ConfirmDialogComponent: typeof import('./components/common/ConfirmDialogComponent.vue')['default']
    DefaultBtn: typeof import('./components/common/button/DefaultBtn.vue')['default']
    DefaultChip: typeof import('./components/common/chips/DefaultChip.vue')['default']
    DelBtn: typeof import('./components/common/button/DelBtn.vue')['default']
    DrawerComponent: typeof import('./components/common/DrawerComponent.vue')['default']
    HelloWorld: typeof import('./components/main/ListComponent.vue')['default']
    LayoutComponent: typeof import('./components/common/LayoutComponent.vue')['default']
    ListComponent: typeof import('./components/main/ListComponent.vue')['default']
    ModBtn: typeof import('./components/common/button/ModBtn.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelectBtn: typeof import('./components/common/button/SelectBtn.vue')['default']
    ViewBtn: typeof import('./components/common/button/ViewBtn.vue')['default']
    VResult: typeof import('./components/common/button/VResult.vue')['default']
  }
}
