/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/FavoritesView': RouteRecordInfo<'/FavoritesView', '/FavoritesView', Record<never, never>, Record<never, never>>,
    '/LogInView': RouteRecordInfo<'/LogInView', '/LogInView', Record<never, never>, Record<never, never>>,
    '/MainViewView': RouteRecordInfo<'/MainViewView', '/MainViewView', Record<never, never>, Record<never, never>>,
    '/MemoryNotesView': RouteRecordInfo<'/MemoryNotesView', '/MemoryNotesView', Record<never, never>, Record<never, never>>,
    '/SolveProblemsView': RouteRecordInfo<'/SolveProblemsView', '/SolveProblemsView', Record<never, never>, Record<never, never>>,
    '/test/TestCreateView': RouteRecordInfo<'/test/TestCreateView', '/test/TestCreateView', Record<never, never>, Record<never, never>>,
    '/test/TestSolveView': RouteRecordInfo<'/test/TestSolveView', '/test/TestSolveView', Record<never, never>, Record<never, never>>,
    '/TestView': RouteRecordInfo<'/TestView', '/TestView', Record<never, never>, Record<never, never>>,
    '/UserView': RouteRecordInfo<'/UserView', '/UserView', Record<never, never>, Record<never, never>>,
  }
}
